services:
  webserver:
    build: .
    ports:
      - "10100:80"
    depends_on:
      - db
    networks:
      - webapp_network

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webapp_network

volumes:
  db_data:

networks:
  webapp_network:
    driver: bridge
