version: '3.8'
services:
  webserver-welcome:
    build: .
    ports:
      - "10100:80"
    volumes:
      - ./Webserver-main:/var/www/html
    depends_on:
      - db
      - webserver-internal
    networks:
      - webapp_network

  webserver-internal:
    image: php:8.1-apache
    container_name: webserver_internal
    volumes:
      - ./Webserver-internal:/var/www/html
    ports:
      - "10200:80"
    networks:
      - webapp_network

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webapp_network

volumes:
  db_data:

networks:
  webapp_network:
    driver: bridge
